# fly.toml app configuration file generated for group-project-car-showroom-white-bird-9462 on 2023-11-30T22:28:47+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "group-project-car-showroom-white-bird-9462"
primary_region = "waw"

[build]

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
