name: 'Build and deploy'

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Deploy to Netlify'
    steps:
      - name: Deploy
        run: |
          curl -L https://fly.io/install.sh | sh
          export FLYCTL_INSTALL="/home/runner/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          flyctl deploy -a="group-project-car-showroom-white-bird-9462" --config='./fly.toml' -t='FlyV1 fm2_lJPECAAAAAAAAc4yxBBabOCLisP+/1oLwnjiuEEOwrVodHRwczovL2FwaS5mbHkuaW8vdjGWAJLOAAV/Sx8Lk7lodHRwczovL2FwaS5mbHkuaW8vYWFhL3YxxDz5w4ZTw7XxFT3vYrSqftGu84PrD7u5BYxf1XGFw0uOEfd8vc7uNONLHQXKuxP9MsPNQbAWAUTP0AiqG7nER/NZxDlkgd9FCSvY0TO3gxqnFKh5hmOsrMO7833vXzLJnO2GiMgSZCnCW72n3N0WP0oxkivy0DhthGj1bzwrf+aN1EMotnNRDZKUA5GBzgAiu9YfBZGCp2J1aWxkZXIfondnHwHEIK87r1mINF5J3kqb4AEdmWBFLTN4xIS0R2JW8Lk3carz,fm2_lJPER/NZxDlkgd9FCSvY0TO3gxqnFKh5hmOsrMO7833vXzLJnO2GiMgSZCnCW72n3N0WP0oxkivy0DhthGj1bzwrf+aN1EMotnNRxBC/mC1Swn9O6Z/FcDFvOwnPw7lodHRwczovL2FwaS5mbHkuaW8vYWFhL3YxlgSSzmVo8cjOZezH5gqRzgAFGoUMxBBfvQPx8TnrOlasZ9HOL21kxCAUlUBPfpEIm0NMWF9OG7RdbiyAJT7Q8Kcc2bAm4qsRlg=='
        shell: bash